#ifndef SCENE_TRIANGULATION_3_COLOR_ITEM_CONFIG_H
#define SCENE_TRIANGULATION_3_COLOR_ITEM_CONFIG_H

#ifdef scene_triangulation_3_color_item_EXPORTS
#  define mesh_3_demo_scene_triangulation_3_color_item_EXPORTS 1
#endif

#ifdef mesh_3_demo_scene_triangulation_3_color_item_EXPORTS
#  define SCENE_TRIANGULATION_3_COLOR_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_TRIANGULATION_3_COLOR_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_TRIANGULATION_3_COLOR_ITEM_CONFIG_H
